export const GET_ALL_CLASS =  'GET_ALL_CLASS';
export const LOGIN = 'LOGIN';
export const TEST = 'TEST';
export const SHOW_LOGIN_MESSAGE = 'SHOW_LOGIN_MESSAGE';
export const GET_CURRENT_USER_NAME = 'GET_CURRENT_USER_NAME';
export const STUDENT_GET_CURRENT_WEEK_CALENDAR = 'STUDENT_GET_CURRENT_WEEK_CALENDAR';