export const GET_ALL_CLASS =  'GET_ALL_CLASS';
export const LOGIN = 'LOGIN';
export const TEST = 'TEST';
export const SHOW_LOGIN_MESSAGE = 'SHOW_LOGIN_MESSAGE';
export const GET_CURRENT_USER_NAME = 'GET_CURRENT_USER_NAME';
export const STUDENT_GET_CURRENT_WEEK_CALENDAR = 'STUDENT_GET_CURRENT_WEEK_CALENDAR';
export const GET_LEARNING_YEAR = 'GET_LEARNING_YEAR';
export const GET_WEEK_NUMBER = 'GET_WEEK_NUMBER';
export const SET_CURRENT_DATE = 'SET_CURRENT_DATE';

export const TEACHER_GET_WEEK_CALENDAR = 'TEACHER_GET_WEEK_CALENDAR';
export const TEACHER_GET_LESSON_DETAIL = 'TEACHER_GET_LESSON_DETAIL';

export const GET_ALL_LESSON = 'GET_ALL_LESSON';
export const GET_ALL_ROOMS_OF_SUBJECT = 'GET_ALL_ROOMS_OF_SUBJECT';

export const TSMD_GET_YEARS_NOT_END = 'TSMD_GET_YEARS_NOT_END';
export const TSMD_GET_SEMESTERS_NOT_END = 'TSMD_GET_SEMESTERS_NOT_END';